# This workflow will build and run tests for ReqCorder
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Test ReqCorder

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25.0'
    
    - name: Test
      run: go test -v ./...

  test-fedora:
    runs-on: ubuntu-latest
    container: fedora:42
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          dnf install -y ca-certificates util-linux
      
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.0'

      - name: Install dependencies
        run: go mod download
        
      - name: Test
        run: |
          useradd -m -s /bin/bash testuser
          chown -R testuser:testuser $(pwd)
          su testuser -c "cd $(pwd) && go test -v ./..."
    
  test-debian:
    runs-on: ubuntu-latest
    container:
      image: debian:13
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.0'
      
      - name: Update cert store
        run: |
          apt-get update
          apt-get install -y ca-certificates

      - name: Install dependencies
        run: go mod download
        
      - name: Test
        run: |
          useradd -m -s /bin/bash testuser
          chown -R testuser:testuser $(pwd)
          su testuser -c "cd $(pwd) && go test -v ./..."
  
  # test-macos-intel:
  #   runs-on: macos-15-intel
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Setup Go
  #       uses: actions/setup-go@v5
  #       with:
  #         go-version: '1.25.0'
        
  #     - name: Test
  #       run: go test -v ./...
  
  # test-macos-arm:
  #   runs-on: macos-15
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Setup Go
  #       uses: actions/setup-go@v5
  #       with:
  #         go-version: '1.25.0'
        
  #     - name: Test
  #       run: go test -v ./...

